-- Database Schema §15/§16 hardening. APPLIED to staging and production 12 July 2026.

-- Database Schema §15/§16 hardening: wrap auth.uid() in a subselect per
-- Supabase's auth_rls_initplan guidance, on every policy this session added.
-- Pre-existing policies (created_by-based) already used this pattern and are untouched.

alter policy "activities_org_delete" on public.activities using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "activities_org_select" on public.activities using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "activities_org_update" on public.activities using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "agent_runs_org_delete" on public.agent_runs using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "agent_runs_org_select" on public.agent_runs using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "agent_runs_org_update" on public.agent_runs using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "audit_events_select" on public.audit_events using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "budgets_select" on public.budgets using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "budgets_update" on public.budgets using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "clients_org_delete" on public.clients using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "clients_org_select" on public.clients using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "clients_org_update" on public.clients using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "compliance_findings_select" on public.compliance_findings using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "cost_rollups_select" on public.cost_rollups using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "deliverables_org_delete" on public.deliverables using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "deliverables_org_select" on public.deliverables using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "deliverables_org_update" on public.deliverables using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "donors_select" on public.donors using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "donors_update" on public.donors using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "eligibility_reports_select" on public.eligibility_reports using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "indicators_org_delete" on public.indicators using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "indicators_org_select" on public.indicators using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "indicators_org_update" on public.indicators using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "knowledge_documents_select" on public.knowledge_documents using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "knowledge_documents_update" on public.knowledge_documents using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "logframe_narratives_select" on public.logframe_narratives using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "logframe_narratives_update" on public.logframe_narratives using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "notification_channels_select" on public.notification_channels using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "notification_channels_update" on public.notification_channels using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "notification_log_select" on public.notification_log using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "notification_rules_select" on public.notification_rules using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "opportunities_select" on public.opportunities using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "opportunities_update" on public.opportunities using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "partners_select" on public.partners using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "partners_update" on public.partners using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "platform_events_select" on public.platform_events using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "project_documents_org_delete" on public.project_documents using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "project_documents_org_select" on public.project_documents using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "project_documents_org_update" on public.project_documents using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "projects_org_delete" on public.projects using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "projects_org_select" on public.projects using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "projects_org_update" on public.projects using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "proposal_sections_select" on public.proposal_sections using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "proposal_sections_update" on public.proposal_sections using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "proposals_select" on public.proposals using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "proposals_update" on public.proposals using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "reports_org_delete" on public.reports using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "reports_org_select" on public.reports using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "reports_org_update" on public.reports using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "risks_org_delete" on public.risks using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "risks_org_select" on public.risks using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "risks_org_update" on public.risks using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "submission_packages_select" on public.submission_packages using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "tasks_select" on public.tasks using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "tasks_update" on public.tasks using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "workflow_instances_select" on public.workflow_instances using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "workflow_instances_update" on public.workflow_instances using (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "audit_events_insert" on public.audit_events with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "budgets_insert" on public.budgets with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "compliance_findings_insert" on public.compliance_findings with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "donors_insert" on public.donors with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "eligibility_reports_insert" on public.eligibility_reports with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "knowledge_documents_insert" on public.knowledge_documents with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "logframe_narratives_insert" on public.logframe_narratives with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "notification_channels_insert" on public.notification_channels with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "notification_rules_insert" on public.notification_rules with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "opportunities_insert" on public.opportunities with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "partners_insert" on public.partners with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "proposal_sections_insert" on public.proposal_sections with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "proposals_insert" on public.proposals with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "submission_packages_insert" on public.submission_packages with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "tasks_insert" on public.tasks with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "workflow_instances_insert" on public.workflow_instances with check (organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));

-- Special-case policies (non-standard predicate)
alter policy "organisation_members_select" on public.organisation_members using (user_id = (select auth.uid()));
alter policy "organisations_select" on public.organisations using (id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "memory_entries_select" on public.memory_entries using (tier = 'institutional' or organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "ai_app_register_select" on public.ai_app_register using (organisation_id is null or organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid())));
alter policy "knowledge_chunks_select" on public.knowledge_chunks using (knowledge_document_id in (select id from public.knowledge_documents where organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid()))));
alter policy "knowledge_chunks_insert" on public.knowledge_chunks with check (knowledge_document_id in (select id from public.knowledge_documents where organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid()))));
alter policy "knowledge_document_links_select" on public.knowledge_document_links using (knowledge_document_id in (select id from public.knowledge_documents where organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid()))));
alter policy "knowledge_document_links_insert" on public.knowledge_document_links with check (knowledge_document_id in (select id from public.knowledge_documents where organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid()))));
alter policy "workflow_instance_history_select" on public.workflow_instance_history using (workflow_instance_id in (select id from public.workflow_instances where organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid()))));
alter policy "workflow_instance_history_insert" on public.workflow_instance_history with check (workflow_instance_id in (select id from public.workflow_instances where organisation_id in (select organisation_id from public.organisation_members where user_id = (select auth.uid()))));

create index if not exists idx_activities_organisation_id on public.activities (organisation_id);
create index if not exists idx_agent_runs_organisation_id on public.agent_runs (organisation_id);
create index if not exists idx_agent_runs_prompt_module_id on public.agent_runs (prompt_module_id);
create index if not exists idx_ai_app_register_organisation_id on public.ai_app_register (organisation_id);
create index if not exists idx_ai_app_register_owner on public.ai_app_register (owner);
create index if not exists idx_audit_events_agent_run_id on public.audit_events (agent_run_id);
create index if not exists idx_audit_events_organisation_id on public.audit_events (organisation_id);
create index if not exists idx_budgets_organisation_id on public.budgets (organisation_id);
create index if not exists idx_budgets_project_id on public.budgets (project_id);
create index if not exists idx_budgets_proposal_id on public.budgets (proposal_id);
create index if not exists idx_clients_organisation_id on public.clients (organisation_id);
create index if not exists idx_compliance_findings_clause_id on public.compliance_findings (clause_id);
create index if not exists idx_compliance_findings_organisation_id on public.compliance_findings (organisation_id);
create index if not exists idx_cost_rollups_organisation_id on public.cost_rollups (organisation_id);
create index if not exists idx_deliverables_organisation_id on public.deliverables (organisation_id);
create index if not exists idx_donors_organisation_id on public.donors (organisation_id);
create index if not exists idx_donors_relationship_owner on public.donors (relationship_owner);
create index if not exists idx_eligibility_reports_opportunity_id on public.eligibility_reports (opportunity_id);
create index if not exists idx_eligibility_reports_organisation_id on public.eligibility_reports (organisation_id);
create index if not exists idx_indicators_organisation_id on public.indicators (organisation_id);
create index if not exists idx_indicators_proposal_id on public.indicators (proposal_id);
create index if not exists idx_knowledge_chunks_knowledge_document_id on public.knowledge_chunks (knowledge_document_id);
create index if not exists idx_knowledge_document_links_knowledge_document_id on public.knowledge_document_links (knowledge_document_id);
create index if not exists idx_knowledge_documents_organisation_id on public.knowledge_documents (organisation_id);
create index if not exists idx_knowledge_documents_supersedes on public.knowledge_documents (supersedes);
create index if not exists idx_logframe_narratives_organisation_id on public.logframe_narratives (organisation_id);
create index if not exists idx_logframe_narratives_project_id on public.logframe_narratives (project_id);
create index if not exists idx_logframe_narratives_proposal_id on public.logframe_narratives (proposal_id);
create index if not exists idx_memory_entries_organisation_id on public.memory_entries (organisation_id);
create index if not exists idx_memory_entries_source_agent_run_id on public.memory_entries (source_agent_run_id);
create index if not exists idx_memory_entries_superseded_by on public.memory_entries (superseded_by);
create index if not exists idx_notification_channels_organisation_id on public.notification_channels (organisation_id);
create index if not exists idx_notification_channels_user_id on public.notification_channels (user_id);
create index if not exists idx_notification_log_channel_id on public.notification_log (channel_id);
create index if not exists idx_notification_log_organisation_id on public.notification_log (organisation_id);
create index if not exists idx_notification_log_platform_event_id on public.notification_log (platform_event_id);
create index if not exists idx_notification_rules_channel_id on public.notification_rules (channel_id);
create index if not exists idx_notification_rules_organisation_id on public.notification_rules (organisation_id);
create index if not exists idx_opportunities_donor_id on public.opportunities (donor_id);
create index if not exists idx_opportunities_organisation_id on public.opportunities (organisation_id);
create index if not exists idx_organisation_members_user_id on public.organisation_members (user_id);
create index if not exists idx_partners_organisation_id on public.partners (organisation_id);
create index if not exists idx_partners_project_id on public.partners (project_id);
create index if not exists idx_partners_proposal_id on public.partners (proposal_id);
create index if not exists idx_project_documents_organisation_id on public.project_documents (organisation_id);
create index if not exists idx_projects_opportunity_id on public.projects (opportunity_id);
create index if not exists idx_projects_organisation_id on public.projects (organisation_id);
create index if not exists idx_prompt_modules_author_id on public.prompt_modules (author_id);
create index if not exists idx_prompt_modules_rolled_back_from on public.prompt_modules (rolled_back_from);
create index if not exists idx_proposal_sections_organisation_id on public.proposal_sections (organisation_id);
create index if not exists idx_proposal_sections_proposal_id on public.proposal_sections (proposal_id);
create index if not exists idx_proposal_sections_workflow_instance_id on public.proposal_sections (workflow_instance_id);
create index if not exists idx_proposals_client_id on public.proposals (client_id);
create index if not exists idx_proposals_opportunity_id on public.proposals (opportunity_id);
create index if not exists idx_proposals_organisation_id on public.proposals (organisation_id);
create index if not exists idx_regulatory_clauses_document_id on public.regulatory_clauses (document_id);
create index if not exists idx_regulatory_clauses_superseded_by on public.regulatory_clauses (superseded_by);
create index if not exists idx_regulatory_documents_supersedes on public.regulatory_documents (supersedes);
create index if not exists idx_reports_organisation_id on public.reports (organisation_id);
create index if not exists idx_risks_organisation_id on public.risks (organisation_id);
create index if not exists idx_submission_packages_organisation_id on public.submission_packages (organisation_id);
create index if not exists idx_submission_packages_proposal_id on public.submission_packages (proposal_id);
create index if not exists idx_submission_packages_submitted_by on public.submission_packages (submitted_by);
create index if not exists idx_tasks_agent_run_id on public.tasks (agent_run_id);
create index if not exists idx_tasks_organisation_id on public.tasks (organisation_id);
create index if not exists idx_tasks_workflow_instance_id on public.tasks (workflow_instance_id);
create index if not exists idx_workflow_instance_history_workflow_instance_id on public.workflow_instance_history (workflow_instance_id);
create index if not exists idx_workflow_instances_organisation_id on public.workflow_instances (organisation_id);
create index if not exists idx_workflow_instances_workflow_definition_id on public.workflow_instances (workflow_definition_id);
